server:
  port: 3030

solon:
  app:
    name: 'demo-app'
    group: 'demo'

  logging:
    appender:
      console:
        level: INFO
      file:
        level: INFO
  dataSources:
    db1!: # 数据源名称是 db1
      class: "com.zaxxer.hikari.HikariDataSource"
      jdbcUrl: jdbc:mysql://localhost:3306/backgroundmanagement_db?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: 679523

easy-query:
  db1: # 必须和 solon.dataSources.db1! 名称一致
    database: mysql  # 数据库方言（mysql、postgresql、sqlserver等）
    print-sql: true  # 打印SQL日志

redis:
  rd1: # 数据源-ds1
    server: localhost:6379  # Redis服务地址
    db: 1 # Redis数据库编号

sa-token:
  token-name: magicToken # Token名称
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  active-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true #旧版曾用名（allow-concurrent-login）
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false